FriendsOfSymfony/FOSHttpCacheBundle

composer.json

I *think* we only needed `minimum-stability: dev` for testing against the dev version of the http-cache library. Unfortunately, all other vendors then got included in their dev versions too. It may be better to work with stable vendor versions (except http-cache) so our tests will suffer less from volatile vendors such as Symfony adding deprecation warnings, for instance. (We catch those warnings for our tests that run against dev version of Symfony thanks to #180.)

Fix Travis buid

---

Resources/doc/features/tagging.rst

Tags are not updatable under `cache_manager` config, but [directly under root node](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/DependencyInjection/Configuration.php#L65-L75).
[Reference doc](http://foshttpcachebundle.readthedocs.org/en/stable/reference/configuration/tags.html) seems correct though.
Tracked on [eZ community forum](http://share.ez.no/forums/ez-publish-5-platform/fos-http-bundle-and-tagging) :wink:

Fixed tagging basic configuration example

---

DependencyInjection/Compiler/SecurityContextPass.php
FOSHttpCacheBundle.php
Resources/config/user_context.xml
Tests/Functional/Fixtures/app/config/config.yml
Tests/Unit/UserContext/RoleProviderTest.php
UserContext/RoleProvider.php

Adding forwards compatibility for Symfony 2.7/3.0. This makes sense for users already switching over from (deprecated) `TokenStorage` to `SecurityContext` in their applications. This reduces deprecation warnings in our tests. We still need some changes in the bundle config to dynamically inject the token storage instead of the security context service.

Better Symfony 2.7/3.0 compatibility

---

.travis.yml
Resources/doc/Makefile
Resources/doc/conf.py
Resources/doc/contributing.rst
Resources/doc/features/invalidation.rst
Resources/doc/features/symfony-http-cache.rst
Resources/doc/features/testing.rst
Resources/doc/includes/enabled.rst
Resources/doc/includes/match.rst
Resources/doc/index.rst
Resources/doc/reference/annotations.rst
Resources/doc/reference/cache-manager.rst
Resources/doc/reference/configuration/cache-manager.rst
Resources/doc/reference/configuration/debug.rst
Resources/doc/reference/configuration/flash-message.rst
Resources/doc/reference/configuration/headers.rst
Resources/doc/reference/configuration/invalidation.rst
Resources/doc/reference/configuration/match.rst
Resources/doc/reference/configuration/proxy-client.rst
Resources/doc/reference/configuration/tags.rst
Resources/doc/reference/configuration/test.rst
Resources/doc/reference/configuration/user-context.rst
Resources/doc/requirements.txt
Resources/doc/spelling_word_list.txt

following the pattern of https://github.com/FriendsOfSymfony/FOSHttpCache/pull/166 i add spell checking to the bundle doc as well.

add spell checking and fix spelling errors

---

Resources/doc/reference/configuration/user-context.rst

to be consistent with FOSHttpCache examples and Symfony HttpCache plugins
fix #189
luckily, the URL only occurs in the documentation, not in actual code. the context listener listens only looks for the accept header and matches every url.

adjust example for user context hash url 

---

DependencyInjection/FOSHttpCacheExtension.php
Resources/config/cache_control_listener.xml
Resources/config/matcher.xml
Tests/Unit/DependencyInjection/Compiler/HashGeneratorPassTest.php
Tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php

Fix #193.
These services where previously defined in `cache_control_listener.xml`. That file, however, was not loaded e.g. when only invalidation (and no cache control) rules were defined. This PR always load the `request_matcher` and `rule_matcher`, so they can be used in `cache_control`, `invalidation` and/or `tags`.

Always load request_matcher and rule_matcher services

---

Resources/doc/features/user-context.rst

while implementing the context in a new project, i noticed that the doc is a bit confusing, mentioning half of the steps but not the route.
i propose we either change as i do in this PR, or remove all documentation examples from the description and link to the reference.

improve user context documentation

---

DependencyInjection/Configuration.php
DependencyInjection/FOSHttpCacheExtension.php
Resources/doc/reference/configuration/cache-manager.rst
Resources/doc/reference/configuration/proxy-client.rst
Tests/Resources/Fixtures/config/full.php
Tests/Resources/Fixtures/config/full.xml
Tests/Resources/Fixtures/config/full.yml
Tests/Unit/DependencyInjection/ConfigurationTest.php

fix #186
This does not handle the test case section, but then i don't think we need to care about that. The test case would need to know about the caching proxy implementation anyways.

allow to configure custom proxy client

---

.travis.yml

This fixes the [variations in code coverage](https://github.com/FriendsOfSymfony/FOSHttpCache/issues/175#issuecomment-81511563) we saw previously, due to hhvm finishing before any of the PHP builds.

Produce code coverage only once

---

DependencyInjection/FOSHttpCacheExtension.php

Using symfony as proxy_client failed.

Fix typo in symfony service filename.

---

DependencyInjection/FOSHttpCacheExtension.php
Tests/Resources/Fixtures/config/symfony.php
Tests/Resources/Fixtures/config/symfony.xml
Tests/Resources/Fixtures/config/symfony.yml
Tests/Unit/DependencyInjection/ConfigurationTest.php
Tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php

the default `tags.enabled: auto` was ignored and treated as `true` but no validation done whether this will actually work.
this change fixes the problem.

fix DI for tag.enabled=auto and add configuration tests

---

Resources/doc/reference/configuration/match.rst

I think it's not very clear for the moment what status code are matched by a rule. I propose to add the list in the documentation, to avoid other problems like https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/224#issuecomment-118378231.

Add a list of default matched status code

---

CHANGELOG.md
EventListener/InvalidationSubscriber.php
Http/RuleMatcher.php
Tests/Functional/EventListener/InvalidationSubscriberTest.php
Tests/Functional/Fixtures/Controller/InvalidationController.php
Tests/Functional/Fixtures/app/config/config.yml
Tests/Functional/Fixtures/app/config/routing.yml

Fix #224. Invalidation was not triggered when the controller returned a response with status codes such as 204 or 302. A more elaborate solution, which involves creating separate, configurable response matchers (as well as request matchers), as described in #69, should be done in a separate PR.

Fix invalidation not being triggered for some status codes

---

Resources/doc/features/helpers/flash-message.rst

When we use this function as it is, we get a javascript error saying:
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
var a=JSON.parse(b);console.log(a);...
```
In the server side, json_encode encrypt the cookie in HTTP, so to parse the cookie we should decrypt that can by using decodeURIComponent javascript function.

Use decodeURIComponent to decode cookie before parsing it

---

Resources/doc/features/helpers/flash-message.rst
Resources/doc/spelling_word_list.txt

see #245
@skonsoft does this make sense?

clarify the javascript side for the flash listener

---

.travis.yml
composer.json

PHP 5.3 is past its end of live date. 
And builds fail with out of memory problems...
https://travis-ci.org/FriendsOfSymfony/FOSHttpCacheBundle/jobs/91344571

drop php 5.3 support

---

DependencyInjection/Compiler/SecurityContextPass.php

The security part is optional in the role provider class, which is why `security.token_storage` is also defined with `on-invalid=ignore`.
As we have security disabled in dev env, neither security.token_storage nor security.context exists, but it still tries to replace the dependency and loses on-invalid=ignore. Then it was complaining, that the service is missing.

Fix dependency on a non-existent service "security.context"

---

DependencyInjection/Configuration.php
Tests/Unit/DependencyInjection/ConfigurationTest.php

With these checks removed you can now specify `enabled: false` on invalidation or tagging configuration sections even if you have previously defined some rules for that section.

Removed over-zealous configuration checks

---

CacheManager.php
Command/InvalidateTagCommand.php
HttpCache.php
Tests/Unit/CacheManagerTest.php
Tests/Unit/HttpCacheTest.php

fix #266
@Tobion am i correct that this should go into the 1.3 branch? we want to delete this things for 2.0 so the deprecations would not really help there. i don't want to build a 1.4 version only for the migration like symfony 2.8 is - too much effort.
also, do you know how to make the deprecations helper not complain about our legacy tests? i tried the `@legacy` annotation on the test cases, but that did not seem help.

trigger deprecation notices for deprecated code

---

CHANGELOG.md
EventListener/UserContextSubscriber.php
Tests/Unit/EventListener/UserContextSubscriberTest.php

I heavily use role provider user context hash  with a ttl of 900s.
A session deconnexion happening while the hash is in cache trigger a situation where you set an anonymous data for an authenticated hash. In this situation there is no breach of security (yeah) but it's definitively a bug.
Proposed solution is to generate a hash at each request and prevent setting cache if hash are not equivalent (ie: roles or situation has changed).
Tests to be added, but I want to start the discussion.
See #273

check sanity of user context hash, if not, prevent setting any cache

---

Resources/doc/features/user-context.rst
Resources/doc/spelling_word_list.txt

see https://github.com/FriendsOfSymfony/FOSHttpCache/pull/292 and https://github.com/FriendsOfSymfony/FOSHttpCache/issues/287

clarify that user context url needs to be available to anonymous users

---

Resources/doc/features/symfony-http-cache.rst

Warning about class caches in Symfony 2.8+.

Updated Symfony HTTP cache docs

---

DependencyInjection/FOSHttpCacheExtension.php
EventListener/UserContextSubscriber.php
Resources/config/user_context.xml
Tests/Unit/EventListener/UserContextSubscriberTest.php
Tests/Unit/UserContext/AnonymousRequestMatcherTest.php
UserContext/AnonymousRequestMatcher.php
composer.json

> Fixes an issue described in #274
The hardcoded anonymous hash might differ from the one used in the sanity check introduced by this PR. This causes cache expirations for us since anonymous requests don't match.
This change excludes anonymous requests, using an `AnonymousRequestMatcher`, from this sanity check.
https://github.com/ezsystems/ezpublish-kernel/pull/1601 describes the consequences and way to reproduce on ezplatform.

Do not sanity check hash of anonymous requests

---

DependencyInjection/Configuration.php
DependencyInjection/FOSHttpCacheExtension.php
Resources/doc/reference/configuration/cache-manager.rst
Tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php

without this fix, a config like the following leads to an error during container building:
```
cache_manager:
custom_proxy_client: "app.caching.rabbitmq_client"
```
`Undefined index: proxy_client`

handle configuration where we only have a custom proxy client and proxies configured

---

CHANGELOG.md
DependencyInjection/Compiler/LoggerPass.php
DependencyInjection/Compiler/TagListenerPass.php
EventListener/AbstractRuleListener.php
EventListener/CacheControlListener.php
EventListener/FlashMessageListener.php
EventListener/InvalidationListener.php
EventListener/TagListener.php
EventListener/UserContextListener.php
FOSHttpCacheBundle.php
Resources/config/cache_control_listener.xml
Resources/config/cache_tagging.xml
Resources/config/flash_message.xml
Resources/config/invalidation_listener.xml
Resources/config/user_context.xml
Resources/doc/features/helpers/flash-message.rst
Resources/doc/features/symfony-http-cache.rst
Resources/doc/features/user-context.rst
Tests/Functional/EventListener/CacheControlListenerTest.php
Tests/Functional/EventListener/InvalidationListenerTest.php
Tests/Functional/EventListener/TagListenerTest.php
Tests/Unit/DependencyInjection/Compiler/TagListenerPassTest.php
Tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php
Tests/Unit/EventListener/CacheControlListenerTest.php
Tests/Unit/EventListener/InvalidationListenerTest.php
Tests/Unit/EventListener/TagListenerTest.php
Tests/Unit/EventListener/UserContextListenerTest.php
Tests/Unit/SymfonyCache/EventDispatchingHttpCacheTest.php

cleanup event listener naming

---

Resources/doc/reference/configuration/headers.rst

@ddeboer just noticed this in one of our projects. and we have no functional test for this one... if you have ideas how to improve the text below the code example, they would be welcome.

we need stdlib.h for the reverse-proxy-ttl handling

---

.travis.yml
composer.json
src/EventListener/CacheControlListener.php
src/EventListener/TagListener.php
tests/Functional/EventListener/CacheControlListenerTest.php
tests/Functional/Fixtures/Controller/TagController.php

Should replace https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/324
Fix deprecated methods
- Add support for Symfony 3.2
- Fix the default private cache control added by Symfony 3.2
- Use `isMethodCacheable` instead of `isMethodSafe` (because it's deprecated)
I hope the new `symfony/http-foundation` restriction is ok.

Symfony 3.2

---

.travis.yml
EventListener/AbstractRuleSubscriber.php
EventListener/CacheControlSubscriber.php
EventListener/TagSubscriber.php
Tests/Functional/EventListener/CacheControlSubscriberTest.php
Tests/Functional/Fixtures/Controller/TagController.php
Tests/Unit/EventListener/CacheControlSubscriberTest.php

Following https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/337 & https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/324
I've added Symfony 3.1 & 3.2 to Travis.
~~There seems to be a strange error on Symfony 3.1 with a _missing_ Twig template ..~~
It seems to appear only on my dev machine.

Add support for Symfony 3.*

---

src/DependencyInjection/Configuration.php
src/EventListener/CacheControlListener.php
tests/Unit/EventListener/CacheControlListenerTest.php

removing a lot that was added in 1.3 to support both older and newest versions of symfony correctly.
apart from getting some fixes in, this will make sure we can merge 1.3 to master again if there are further fixes to 1.3.

merge 1.3 to master

---

CHANGELOG.md
Resources/doc/includes/safe.rst
Resources/doc/reference/configuration/cacheable.rst
Resources/doc/reference/glossary.rst
src/DependencyInjection/Configuration.php

follow up of #354
reading through the changes, i realized that expression leads to default status codes being ignored. i think that is fine, but wanted to make the documentation clear about that.

clarify documentation of cacheable response status

---

CHANGELOG.md
src/DependencyInjection/FOSHttpCacheExtension.php
src/EventListener/UserContextListener.php
src/Resources/config/user_context.xml
tests/Unit/EventListener/UserContextListenerTest.php

Refactor UserContextListener to take options array

---

.travis.yml
src/DependencyInjection/FOSHttpCacheExtension.php
tests/Unit/DependencyInjection/Compiler/HashGeneratorPassTest.php

realized that we don't test with symfony 3.3. and hhvm build works but sphinx does not - actually building the doc once is enough.

build for symfony 3.3 and only spellcheck in one build

---

src/EventListener/InvalidationListener.php

This event is deprecated since symfony 3.3. And listening to it seems useless here anyway because the terminate event is already used which is triggered after the exception event in any case. So they are not exclusive.

Fix deprecated console.exception event

---

DependencyInjection/Compiler/TagSubscriberPass.php

From version 4.0 and up, `ControllerListener` service from `SensioFrameworkExtraBundle` has been renamed to use FQCN as service name, so this adds support for the old and new name.
`master` branch also needs this fix, however, the compiler pass has been renamed to `TagListenerPass`, so probably needs manual merge.

Support FQCN service names for Sensio Framework Extra Bundle

---

EventListener/UserContextSubscriber.php
Tests/Unit/EventListener/UserContextSubscriberTest.php

without the setSharedMaxAge the cache control listener will still add an s-maxage which is at least confusing and depending on caching proxy implementation could void the no-cache.
also, symfony httpcache looks only for no-store and private, but not for no-cache when deciding if it may cache.
fix #399

make sure no caching happens when hash mismatch

---

tests/Unit/CacheManagerTest.php
tests/Unit/Command/BaseInvalidateCommandTest.php
tests/Unit/Command/InvalidatePathCommandTest.php
tests/Unit/Command/InvalidateRegexCommandTest.php
tests/Unit/Command/InvalidateTagCommandTest.php
tests/Unit/Command/PathSanityCheckTest.php
tests/Unit/Command/RefreshPathCommandTest.php
tests/Unit/Configuration/InvalidateRouteTest.php
tests/Unit/Configuration/TagTest.php
tests/Unit/DependencyInjection/Compiler/HashGeneratorPassTest.php
tests/Unit/DependencyInjection/Compiler/LoggerPassTest.php
tests/Unit/DependencyInjection/Compiler/TagListenerPassTest.php
tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php
tests/Unit/EventListener/CacheControlListenerTest.php
tests/Unit/EventListener/InvalidationListenerTest.php
tests/Unit/EventListener/TagListenerTest.php
tests/Unit/EventListener/UserContextListenerTest.php
tests/Unit/Http/RequestMatcher/QuerystringRequestMatcherTest.php
tests/Unit/Http/RuleMatcherTest.php
tests/Unit/Http/SymfonyResponseTaggerTest.php
tests/Unit/UserContext/AnonymousRequestMatcherTest.php
tests/Unit/UserContext/RequestMatcherTest.php
tests/Unit/UserContext/RoleProviderTest.php

I use the `PHPUnit\Framework\TestCase` notation instead of `PHPUnit_Framework_TestCase` while extending our TestCases. This will help us migrate to PHPUnit 6, that [no longer support snake case class names](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).

Use PHPUnit\Framework\TestCase instead of PHPUnit_Framework_TestCase

---

CHANGELOG.md
Resources/doc/reference/configuration/user-context.rst
src/DependencyInjection/FOSHttpCacheExtension.php
src/Resources/config/user_context.xml
src/Security/Http/Logout/ContextInvalidationLogoutHandler.php
src/Security/Http/Logout/ContextInvalidationLogoutSuccessHandler.php
src/Security/Http/Logout/ContextInvalidationSessionLogoutHandler.php
src/UserContextInvalidator.php
tests/Functional/Fixtures/app/config/config.yml
tests/Functional/Security/Http/Logout/ContextInvalidationLogoutHandlerTest.php

Fix ContextInvalidationLogoutHandler

---

Resources/doc/contributing.rst

I've used the same wording (THE Slack, apparently that's a thing :-)) as in the official Symfony docs (https://github.com/symfony/symfony-docs/blob/ef9781257b47b2923b32c6d27f73acd38fc83b70/contributing/code/bugs.rst).

Added slack info

---

.travis.yml
CHANGELOG.md
DependencyInjection/FOSHttpCacheExtension.php
EventListener/SessionListener.php
Resources/config/user_context.xml
Tests/Resources/Fixtures/config/empty.yml
Tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php
Tests/Unit/EventListener/SessionListenerTest.php
composer.json

Backport of #435 to v1.3
Let's see what happens.
@Toflar I hope you don't mind, I squashed your commits.

[1.3] Decorate default Symfony session listener for Symfony 3.4+ to restore user context functionality

---

CHANGELOG.md
src/DependencyInjection/FOSHttpCacheExtension.php
src/EventListener/SessionListener.php
src/EventListener/UserContextListener.php
tests/Functional/EventListener/UserContextListenerTest.php
tests/Functional/Fixtures/Controller/TestController.php
tests/Functional/Fixtures/app/config/config.yml
tests/Functional/Fixtures/app/config/routing.yml
tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php

Use https://github.com/symfony/symfony/pull/26681 to make the session listener work with Symfony 4.1
Fix #437
Replaces #438

adjust session listener to symfony 4.1

---

src/Http/ResponseMatcher/ExpressionResponseMatcher.php
tests/Unit/Http/RequestMatcher/QuerystringRequestMatcherTest.php
tests/Unit/Http/ResponseMatcher/CacheableResponseMatcherTest.php
tests/Unit/Http/ResponseMatcher/ExpressionResponseMatcherTest.php
tests/Unit/Http/ResponseMatcher/NonErrorResponseMatcherTest.php
tests/Unit/Http/RuleMatcherTest.php
tests/Unit/Http/SymfonyResponseTaggerTest.php

- added unit tests
- cleanup expression matcher to allow any expression language and not just symfony framework bundle ones
- do work when optional dependency framework extra bundle is not available

test response matchers

---

CHANGELOG.md
Resources/doc/reference/configuration/user-context.rst
src/FOSHttpCacheBundle.php

This would reduce some configuration. Right now we can autoconfigure almost all services, except our custom context provider.

Autoconfigure custom context providers

---

CHANGELOG.md
EventListener/SessionListener.php
Tests/Unit/EventListener/SessionListenerTest.php

Add SessionListener::onFinishRequest method to work with Symfony 3.4.12

---

CHANGELOG.md
composer.json
src/EventListener/SessionListener.php
tests/Unit/EventListener/SessionListenerTest.php

```
- symfony/lts v3 conflicts with symfony/routing[4.1.x-dev].
- symfony/lts v3 conflicts with symfony/routing[v4.1.0].
- symfony/lts v3 conflicts with symfony/routing[v4.1.0-BETA1].
- symfony/lts v3 conflicts with symfony/routing[v4.1.0-BETA2].
- symfony/lts v3 conflicts with symfony/routing[v4.1.0-BETA3].
- symfony/lts v3 conflicts with symfony/routing[v4.1.1].
- symfony/lts v3 conflicts with symfony/routing[v4.1.2].
- symfony/lts v3 conflicts with symfony/routing[v4.1.3].
- Installation request for symfony/lts ^3 -> satisfiable by symfony/lts[v3].
- Installation request for symfony/routing 4.1.*@dev -> satisfiable by symfony/routing[4.1.x-dev, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.2, v4.1.3].
```
Closes …

Fixed dependency error, update master from 1.3

---

src/DependencyInjection/Configuration.php

This should fix a deprecation notice in the upcoming Symfony 4.2 release.
> Deprecated constructing a TreeBuilder without passing root node information.
To be merged after https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/476

Fix Symfony 4.2 deprecation notice

---

src/EventListener/UserContextListener.php
tests/Unit/EventListener/UserContextListenerTest.php

This moves logic to set NoAutoCacheControl so it is always executed if
vary header exists, now also when that is the case from response already.
Also adds unit test coverage for this feature.

Fix missing NoAutoCacheControl when vary on contex hash is set from Response

---

CHANGELOG.md
composer.json
src/Http/SymfonyResponseTagger.php
tests/Unit/Http/SymfonyResponseTaggerTest.php

requires https://github.com/FriendsOfSymfony/FOSHttpCache/pull/430 and a new patch release of the library.

clear response tagger after tagging to not leak tags from one response to the next

---

Resources/doc/features/symfony-http-cache.rst
Resources/doc/reference/configuration/proxy-client.rst

choosing some duplication of doc from the library to make things more understandable and less confusing.
fix #490

clarify how to use the symfony kernel dispatcher

---

Resources/doc/conf.py
Resources/doc/requirements.txt

This should hopelly fix the code highlighting in the docs:
based on: https://github.com/sphinx-doc/sphinx/issues/3215#issuecomment-368623135

Fix readthedocs code highlighting

---

Resources/doc/features/symfony-http-cache.rst

Based on the symfony docs enable method override is enabled by default so we should also add Request:: enableHttpMethodParameterOverride() by default?
https://symfony.com/doc/current/reference/configuration/framework.html#http-method-override

Added link to symfony httpcache docs for http_method_override

---

Resources/doc/conf.py
Resources/doc/requirements.txt

#495 did not fix the code highlighting
- add `sphinxcontrib-phpdomain` as correct requirements
- update `sphinx_rtd_theme` and use it in the ci
- activate `phpdoc` from sensio

Fix requirements sphinxcontrib-phpdomain and use newest rtd theme

---

CHANGELOG.md
src/DependencyInjection/Compiler/SessionListenerPass.php
src/EventListener/UserContextListener.php
src/FOSHttpCacheBundle.php
src/Resources/config/user_context.xml
tests/Unit/EventListener/UserContextListenerTest.php

do not leak the Symfony-Session-NoAutoCacheControl header when the Symfony session system is not enabled.

---

Resources/doc/reference/annotations.rst

While this should be evident, it helps people to document this explicitly.

Explain invalidation applies to unsafe requests

---

src/DependencyInjection/FOSHttpCacheExtension.php

Related to #521 
allow things like 
```
parameters:
env(VARNISH_SERVER): "varnish1.test"
env(VARNISH_BASE_URL): "site.test"
fos_http_cache:
proxy_client:
varnish:
http: 
servers: ['%env(json:VARNISH_HTTP)%']
base_url: '%env(json:VARNISH_BASE_URL)%'
```

Do not validate configuration when environment parameters are used

---

src/Resources/config/cache_manager_commands.xml

no need to specify the command names in the config file anymore, we use the static property now.

cleanup command service definition

---

src/UserContext/RoleProvider.php
tests/Unit/UserContext/RoleProviderTest.php

Symfony deprecate the method `getRole` in favor of `getRoleNames`.
This PR update the RoleProvider to check the current behavior of symfony and use the best method.

Fix deprecation for TokenInterface::getRoles

---

src/DependencyInjection/Configuration.php
tests/Unit/DependencyInjection/ConfigurationTest.php

Finishes #486
Fixes https://github.com/FriendsOfSymfony/FOSHttpCache/issues/456

Fix InvalidConfigurationException message after TagCapable support in logout_handler

---

src/Command/BaseInvalidateCommand.php

This gets rid of the deprecation message on Symfony 4.2.
I've copied the `getContainer` method from `ContainerAwareCommand` to the command since the intention is to remove the usage of the container anyway for v3 of the bundle.

Use ContainerAwareTrait instead of deprecated ContainerAwareCommand

---

CHANGELOG.md
composer.json

lets wait with merging until php-http/client-common has a 2.0 release and we see php-http/guzzle6-adapter 2.0 being installed in the travis build.
also needs https://github.com/FriendsOfSymfony/FOSHttpCache/pull/442 merged and tagged first.

test with httplug 2

---

composer.json

symfony 3 seems also vulnerable and we should bump the minimum version there too: https://github.com/advisories/GHSA-g996-q5r8-w7g2

bump symfony 3 version because security alert

---

Resources/doc/reference/configuration/proxy-client.rst

xkey-purge option where only described in `tag_mode` section.

Add description on tags_header options when using xkey

---

.styleci.yml
.travis.yml
composer.json
phpunit.xml.dist
src/Security/Http/Logout/ContextInvalidationLogoutHandler.php
tests/Functional/DependencyInjection/ServiceTest.php
tests/Functional/EventListener/CacheControlListenerTest.php
tests/Functional/Security/Http/Logout/ContextInvalidationLogoutHandlerTest.php
tests/Unit/CacheManagerTest.php
tests/Unit/Command/InvalidatePathCommandTest.php
tests/Unit/Command/InvalidateRegexCommandTest.php
tests/Unit/Command/InvalidateTagCommandTest.php
tests/Unit/Command/RefreshPathCommandTest.php
tests/Unit/Configuration/InvalidateRouteTest.php
tests/Unit/Configuration/TagTest.php
tests/Unit/DependencyInjection/Compiler/HashGeneratorPassTest.php
tests/Unit/DependencyInjection/Compiler/TagListenerPassTest.php
tests/Unit/DependencyInjection/ConfigurationTest.php
tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php
tests/Unit/EventListener/CacheControlListenerTest.php
tests/Unit/EventListener/InvalidationListenerTest.php
tests/Unit/EventListener/TagListenerTest.php
tests/Unit/EventListener/UserContextListenerTest.php
tests/Unit/UserContext/RoleProviderTest.php

Locally I run into the following problem:
> PHP Fatal error:  Declaration of FOS\HttpCacheBundle\Tests\Unit\CacheManagerTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in ~/Sulu/sulu-develop.localhost/vendor/friendsofsymfony/http-cache-bundle/tests/Unit/CacheManagerTest.php on line 28
> Fatal error: Declaration of FOS\HttpCacheBundle\Tests\Unit\CacheManagerTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in ~/Sulu/sulu-develop.localhost/vendor/friendsofsymfony/http-cache-bundle/tests/Unit/CacheManagerTest.php on line 28
This seems to be fixed by using:
```xml
<server name="SYMFONY_PHPUNIT_VERSION" value="6.5" />
```
Which seems to be set in the [.travis.yml](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/396eea2c79 …

Fix CI Build and update PHPUnit

---

src/EventListener/UserContextListener.php
tests/Unit/EventListener/UserContextListenerTest.php

Regarding discussion on user hash change detection, this is what I had in mind:
- Makes sure we generate hash to compare with on response => In case hash changed during current request
- Given we only generate hash if `! isAnonymous()` as a performance tweak => Still keep track of if user was logged in at request time, in case that changed in the meantime
TODO:

[Hash] Improve user hash change detection during request by comparing at the end

---

src/EventListener/FlashMessageListener.php
tests/Functional/EventListener/FlashMessageListenerTest.php
tests/Functional/Fixtures/Controller/FlashMessageController.php
tests/Functional/Fixtures/app/config/routing.yml
tests/Functional/Fixtures/app/config/routing_41.yml

1. Add a flash message on a controller
2. Return a `RedirectResponse` from that controller to another one
3. Add another flash message on the second controller
The `flashes` cookie should contain both messages
When the second controller adds the flash message, the `FlashMessageListener` tries to get the cookie from the response header and can't find it, thus doesn't merge the old message with the new one in the newly formed cookie.
Check if the request is a redirect and only set the cookie to the last response

[Bug] Flash messages are overwritten with redirects

---

.github/workflows/php.yml
CHANGELOG.md
src/EventListener/FlashMessageListener.php
tests/Functional/EventListener/FlashMessageListenerTest.php

array_merge_recursive rather than delay setting the flash messages cookie

---

CHANGELOG.md
Resources/doc/reference/configuration/proxy-client.rst
src/DependencyInjection/Configuration.php
src/DependencyInjection/FOSHttpCacheExtension.php
tests/Resources/Fixtures/config/servers_from_jsonenv.php
tests/Resources/Fixtures/config/servers_from_jsonenv.xml
tests/Resources/Fixtures/config/servers_from_jsonenv.yml
tests/Unit/DependencyInjection/ConfigurationTest.php
tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php

I tried to solve #521 with this pull request:
in addition to the regular case (array of servers) the configuration for `varnish.servers` can now be a string holding an environment variable. The environment variable is supposed to be a string that contains a json array of servers.
This solves the problem, that the same app under different environments might have different server configurations. Eg some test setup might have one varnish and a production setup might have three varnish.
To solve the issue, I had to loosen the checks in `Configuration.php` a bit.

feat: support env var in varnish config for servers key

---

src/DependencyInjection/Configuration.php
tests/Functional/DependencyInjection/ServersFromEnvTest.php
tests/Functional/DependencyInjection/ServiceTest.php
tests/Functional/DependencyInjection/ServicesPublicPass.php
tests/Functional/Fixtures/app/AppKernel.php
tests/Functional/Fixtures/app/config/config3.yml
tests/Functional/Fixtures/app/config/config_41.yml
tests/Functional/Fixtures/app/config/config_50.yml
tests/Functional/Fixtures/app/config/config_servers_from_env.yml

There was an error in the configuration definition for `servers_from_jsonenv`: 
The variable was defined as scalarNode, however as the environment variable would be marked as 'json' it would yield in an error 'Array not allowed'. If the incoming env var would be a string, then it would yield later in an error, because an array is expected.
So the proposition is to loosen up the configuration definition and use `variableNode`. This is basically the only change I made.
In addition I added an integration test, to see, if an environment variable is correctly injected into HttpDispatcher. However the test doesn't follow best practice as it needs reflection to get access to the servers variable. I can remove the test if you think it doesn't add additional value.

Fix servers from env vars

---

tests/Functional/EventListener/UserContextListenerTest.php
tests/Functional/Fixtures/app/config/config.yml

While debugging Symfony 6 test case. I did found out that the authentication does on the existing master branch not work like expected.
The test is actually sending `user` as username but actually if you debug and output: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/36159bbac615d0e4e804d1c43e9ef88123f6a82b/src/UserContext/RoleProvider.php#L60
It is just empty. That is because http_basic is not activated and so the user not logged in.
So the hash which was actually tested is incorrect for `user` and is the hash for not `user`. I addded a data provider so a test runs against different users.

Fix test cases for user context listener with different http basic authentication

---

Resources/doc/requirements.txt

as explained in https://github.com/readthedocs/readthedocs.org/issues/9037

lock jinja2 version to avoid BC break
