FriendsOfSymfony/FOSHttpCacheBundle

- Tests/Functional/Fixtures/app/config/config.yml
- Tests/Unit/UserContext/RoleProviderTest.php
https://github.com/symfony/symfony/issues/13710 has been fixed.
> Revert our workaround because Symfony is fixed

- CHANGELOG.md
- Resources/config/tag_listener.xml
- Resources/doc/features/tagging.rst
- Resources/doc/spelling_word_list.txt
- Tests/Functional/EventListener/TagSubscriberTest.php
- Tests/Functional/Fixtures/Controller/TagController.php
- Tests/Functional/Fixtures/app/Resources/views/tag.html.twig
- Tests/Functional/Fixtures/app/config/routing.yml
- Tests/Unit/DependencyInjection/Compiler/HashGeneratorPassTest.php
- Twig/CacheTagExtension.php
> Adding support for tagging from twig

- .scrutinizer.yml
- .travis.yml
See FriendsOfSymfony/FOSHttpCacheBundle#216.
> Set Scrutinizer external coverage timeout

- DependencyInjection/FOSHttpCacheExtension.php
- Resources/config/cache_manager.xml
- Resources/config/cache_tagging.xml
- Resources/doc/reference/configuration/tags.rst
> Cleanup tag handling

- DependencyInjection/Configuration.php
- Tests/Resources/Fixtures/config/custom-client.php
- Tests/Resources/Fixtures/config/custom-client.xml
- Tests/Resources/Fixtures/config/custom-client.yml
- Tests/Unit/DependencyInjection/ConfigurationTest.php
> fix how to configure a custom proxy client for the cache manager

- .travis.yml
- DependencyInjection/FOSHttpCacheExtension.php
- Resources/config/nginx.xml
- Resources/config/nginx_test_client.xml
- Resources/config/varnish.xml
- Resources/config/varnish_test_client.xml
- Tests/Unit/DependencyInjection/Compiler/HashGeneratorPassTest.php
Test against Symfony 2.8. Fix #238.
> Test against Symfony 2.8

- DependencyInjection/FOSHttpCacheExtension.php
- Tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php
fixes #257 as requested @ https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/258
> [proxy client] guzzle client config fix

- .travis.yml
- composer.json
lets hope the out of memory error on 5.3 goes away with this. and we where missing the --prefer-lowest build.
> build 5.3 in prefer-lowest

- Resources/doc/features/helpers/flash-message.rst
Hi,
This is a little precision in the flash messages documentation.
I had some troubles when I was using the current example (the flash message was still appearing after page reload), but this tweak solved it.
I hope it could help :smile:
> flashbag message doc precision

- Resources/doc/features/user-context.rst
> hint when using user context hash together with fos rest format listener

- .travis.yml
- composer.json
I made a similar to https://github.com/FriendsOfSymfony/FOSHttpCache/pull/290
> chore: add phpunit to require-dev for testing

- DependencyInjection/Configuration.php
follow-up on #313 to fail with a more precise message
> custom proxy client may not be empty

- SymfonyCache/EventDispatchingHttpCache.php
Fixed the documentation concerning the option value for disabling the UserContextSubscriber
> Fixed documentation

- composer.json
- doc/reference/configuration/cache-manager.rst
- doc/reference/configuration/user-context.rst
- src/CacheManager.php
- src/Security/Http/Logout/ContextInvalidationLogoutHandler.php
- src/UserContext/RoleProvider.php
- tests/Unit/CacheManagerTest.php
- tests/Unit/Http/SymfonyResponseTaggerTest.php
See https://github.com/FriendsOfSymfony/FOSHttpCache/pull/335
> Remove interface suffix

- src/Resources/config/user_context.xml
Related to https://github.com/FriendsOfSymfony/FOSHttpCache/pull/336
> Renamed the HashGenerator to DefaultHashGenerator

- Resources/doc/reference/configuration/proxy-client.rst
- Resources/doc/spelling_word_list.txt
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/FOSHttpCacheExtension.php
- src/Resources/config/noop.xml
- tests/Resources/Fixtures/config/noop.php
- tests/Resources/Fixtures/config/noop.xml
- tests/Resources/Fixtures/config/noop.yml
- tests/Unit/DependencyInjection/ConfigurationTest.php
- tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php
> Support Noop client

- src/EventListener/FlashMessageListener.php
> Use OptionsResolver in event listener

- Resources/doc/reference/configuration/tags.rst
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/FOSHttpCacheExtension.php
- src/Resources/config/cache_tagging.xml
- tests/Resources/Fixtures/config/tags_strict.php
- tests/Resources/Fixtures/config/tags_strict.xml
- tests/Resources/Fixtures/config/tags_strict.yml
- tests/Unit/DependencyInjection/ConfigurationTest.php
> Add tags.strict config param

- Resources/doc/reference/configuration/headers.rst
- src/DependencyInjection/Configuration.php
- src/EventListener/CacheControlListener.php
- tests/Unit/EventListener/CacheControlListenerTest.php
> Add support for no-store

- Resources/doc/features/user-context.rst
- Resources/doc/spelling_word_list.txt
squashed #363 and simplified the language.
> Added a note about the replay-headers-bundle

- src/Command/InvalidatePathCommand.php
- src/Command/PathSanityCheck.php
- src/Command/RefreshPathCommand.php
- tests/Unit/Command/PathSanityCheckTest.php
> sanity check paths in path based invalidation commands

- CHANGELOG.md
- Resources/doc/reference/configuration/headers.rst
- composer.json
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/FOSHttpCacheExtension.php
- src/EventListener/CacheControlListener.php
- src/Http/ResponseMatcher/ExpressionResponseMatcher.php
- src/Resources/config/cache_control_listener.xml
- tests/Resources/Fixtures/config/full.php
- tests/Resources/Fixtures/config/full.xml
- tests/Resources/Fixtures/config/full.yml
- tests/Unit/DependencyInjection/ConfigurationTest.php
- tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php
- tests/Unit/EventListener/CacheControlListenerTest.php
> cache control listener needs to also look at response

- tests/Functional/DependencyInjection/ServiceTest.php
- tests/Functional/Fixtures/app/Resources/varnish/fos.vcl
- tests/Functional/Fixtures/app/config/config.yml
- tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php
> test that services can actually be loaded

- tests/Unit/EventListener/CacheControlListenerTest.php
> test weak and strong etag on CacheControlListener

- src/EventListener/UserContextListener.php
- tests/Unit/EventListener/UserContextListenerTest.php
> 1.3 to master

- CHANGELOG.md
- src/Configuration/InvalidateRoute.php
- src/Configuration/Tag.php
- src/DependencyInjection/Configuration.php
- src/Security/Http/Logout/ContextInvalidationLogoutHandler.php
- tests/Functional/EventListener/FlashMessageListenerTest.php
- tests/Functional/Fixtures/app/AppKernel.php
- tests/Unit/EventListener/CacheControlListenerTest.php
- tests/Unit/UserContext/RoleProviderTest.php
fixing the changelog and some code style issues
> cleanup before 2.2 alpha release

- CHANGELOG.md
- Resources/doc/features/invalidation.rst
- Resources/doc/features/tagging.rst
- Resources/doc/reference/configuration/proxy-client.rst
- Resources/doc/reference/configuration/tags.rst
- composer.json
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/FOSHttpCacheExtension.php
- src/Resources/config/symfony.xml
- tests/Functional/DependencyInjection/ServiceTest.php
- tests/Resources/Fixtures/config/symfony.php
- tests/Resources/Fixtures/config/symfony.xml
- tests/Resources/Fixtures/config/symfony.yml
- tests/Unit/DependencyInjection/ConfigurationTest.php
- tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php
fix #403
@Toflar is this all that is needed or am i missing something?
> allow cache tag invalidation with symfony HttpCache

- CHANGELOG.md
- Resources/doc/reference/configuration/proxy-client.rst
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/FOSHttpCacheExtension.php
- tests/Resources/Fixtures/config/symfony.php
- tests/Resources/Fixtures/config/symfony.xml
- tests/Resources/Fixtures/config/symfony.yml
- tests/Unit/DependencyInjection/ConfigurationTest.php
> allow to configure purge method for symfony proxy client

- src/Command/InvalidateTagCommand.php
- src/Resources/config/cache_manager.xml
> Improved commands

- CHANGELOG.md
- src/DependencyInjection/FOSHttpCacheExtension.php
- src/EventListener/SessionListener.php
- src/Resources/config/user_context.xml
- tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php
- tests/Unit/EventListener/SessionListenerTest.php
Fix for https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/433.
> Decorate default Symfony session listener for Symfony 3.4+

- tests/Functional/EventListener/UserContextListenerTest.php
- tests/Functional/Fixtures/app/config/config.yml
- tests/Functional/Fixtures/app/config/routing.yml
> testing that user context request is handled correctly

- CHANGELOG.md
- src/DependencyInjection/Compiler/SessionListenerRemovePass.php
- src/FOSHttpCacheBundle.php
fix problem introduced in #435, replace #444
> when sessions are not enabled, the listener does not exist either

- CHANGELOG.md
- DependencyInjection/Compiler/SessionListenerRemovePass.php
- FOSHttpCacheBundle.php
Backport of #445 to 1.3 branch.
> [1.3] when sessions are not enabled, the listener does not exist either

- CHANGELOG.md
- Resources/doc/features/helpers/flash-message.rst
- Resources/doc/features/invalidation.rst
- Resources/doc/features/symfony-http-cache.rst
- Resources/doc/features/tagging.rst
- Resources/doc/reference/cache-manager.rst
- Resources/doc/reference/configuration/headers.rst
- Resources/doc/reference/configuration/proxy-client.rst
- composer.json
- src/DependencyInjection/FOSHttpCacheExtension.php
- src/Resources/config/cache_control_listener.xml
- src/Resources/config/cache_manager.xml
- src/Resources/config/cache_tagging.xml
- src/Resources/config/nginx.xml
- src/Resources/config/noop.xml
- src/Resources/config/symfony.xml
- src/Resources/config/varnish.xml
> support symfony 4 autowiring and adjust doc to autowiring

- tests/Functional/Fixtures/app/config/routing_41.yml
thanks https://twitter.com/rpkamp82
> use explicit controller instead of route default

- src/DependencyInjection/Configuration.php
- tests/Resources/Fixtures/config/user_context_auto_banclient.yml
- tests/Resources/Fixtures/config/user_context_auto_noclient.yml
- tests/Resources/Fixtures/config/user_context_auto_notbanclient.yml
- tests/Resources/Fixtures/config/user_context_true_banclient.yml
- tests/Resources/Fixtures/config/user_context_true_noclient.yml
- tests/Resources/Fixtures/config/user_context_true_notbanclient.yml
- tests/Unit/DependencyInjection/ConfigurationTest.php
> fix user context logout handler auto enabled to not load it when the proxy client is not ban capable

- CHANGELOG.md
- Resources/doc/features/helpers/flash-message.rst
- Resources/doc/features/tagging.rst
- Resources/doc/reference/cache-manager.rst
- Resources/doc/reference/configuration/flash-message.rst
- Resources/doc/reference/configuration/proxy-client.rst
- Resources/doc/reference/configuration/tags.rst
- Resources/doc/reference/configuration/user-context.rst
- Resources/doc/spelling_word_list.txt
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/FOSHttpCacheExtension.php
- src/Resources/config/cache_tagging.xml
- tests/Unit/DependencyInjection/ConfigurationTest.php
- tests/Unit/DependencyInjection/FOSHttpCacheExtensionTest.php
> Added configuration setting for enabling xkey tagging

- .travis.yml
> more specific versions on very old builds

- Resources/doc/features/symfony-http-cache.rst
sorry seems like I broke the link 🙈
> Fixed symfony httpcache documentation link

- Resources/doc/reference/configuration/cache-manager.rst
the documentation was confusing, see #513
> update cache manager doc

- src/Command/InvalidatePathCommand.php
- src/Command/InvalidateRegexCommand.php
- src/Command/InvalidateTagCommand.php
- src/Command/RefreshPathCommand.php
See https://github.com/symfony/symfony/pull/33775
> Command::execute must return int type

- src/EventListener/Php8AttributesListener.php
Sorry, I found a typo in my PR :-/ 
We need to use ControllerResolverInterface as type instead of Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver
> Error in Php8AttributesListener

- .github/workflows/php.yml
- CHANGELOG.md
- src/DependencyInjection/Configuration.php
- src/EventListener/InvalidationListener.php
- src/EventListener/TagListener.php
> do not fail when expression language is not needed

- Resources/doc/requirements.txt
- composer.json
- tests/Functional/Fixtures/Controller/TagAttributeController.php
* fixing cs issue
* pinning docutils because https://github.yuuza.net/sphinx-doc/sphinx/issues/9727
> fix code rot in the ci setup

- src/EventListener/CacheControlListener.php
- src/Http/RequestMatcher/QuerystringRequestMatcher.php
- tests/Unit/Http/RequestMatcher/QuerystringRequestMatcherTest.php
Hi,
I use the projet with PHP 8.1 and I've found 2 deprecated.
> php 8.1 : Fix deprecated
